/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {StringFieldPresentation} from "./string-field-presentation";
import {BooleanRadioGroupFieldPresentation} from "./boolean-radio-group-field-presentation";
import {LinkFieldPresentation} from "./link-field-presentation";
import {ImageLinkFieldPresentation} from "./image-link-field-presentation";
import {DateFieldPresentation} from "./date-field-presentation";
import {HtmlFieldPresentation} from "./html-field-presentation";
import {RichTextFieldPresentation} from "./rich-text-field-presentation";
import {DropdownFieldPresentation} from "./dropdown-field-presentation";
import {MultiSelectFieldPresentation} from "./multi-select-field-presentation";
import {RadioGroupFieldPresentation} from "./radio-group-field-presentation";
import {SelectableFieldGroupPresentation} from "./selectable-field-group-presentation";
import {OpenUiExtensionFieldPresentation} from "./open-ui-extension-field-presentation";

/**
 * presentation properties of the field 
 * @export
 * @interface ContentTypeFieldPresentation
 */
export interface ContentTypeFieldPresentation {
    /**
     * the caption used for this field in UIs
     * @type {string}
     * @memberof ContentTypeFieldPresentation
     */
    caption: StringFieldPresentation | BooleanRadioGroupFieldPresentation | LinkFieldPresentation | ImageLinkFieldPresentation | DateFieldPresentation | HtmlFieldPresentation | RichTextFieldPresentation | DropdownFieldPresentation | MultiSelectFieldPresentation | RadioGroupFieldPresentation | SelectableFieldGroupPresentation | OpenUiExtensionFieldPresentation | ContentTypeFieldPresentation;
    /**
     * the hint used for this field in UIs
     * @type {string}
     * @memberof ContentTypeFieldPresentation
     */
    hint: StringFieldPresentation | BooleanRadioGroupFieldPresentation | LinkFieldPresentation | ImageLinkFieldPresentation | DateFieldPresentation | HtmlFieldPresentation | RichTextFieldPresentation | DropdownFieldPresentation | MultiSelectFieldPresentation | RadioGroupFieldPresentation | SelectableFieldGroupPresentation | OpenUiExtensionFieldPresentation | ContentTypeFieldPresentation;
    /**
     * layoutColumn index used for positioning the field
     * @type {number}
     * @memberof ContentTypeFieldPresentation
     */
    layoutColumn?: StringFieldPresentation | BooleanRadioGroupFieldPresentation | LinkFieldPresentation | ImageLinkFieldPresentation | DateFieldPresentation | HtmlFieldPresentation | RichTextFieldPresentation | DropdownFieldPresentation | MultiSelectFieldPresentation | RadioGroupFieldPresentation | SelectableFieldGroupPresentation | OpenUiExtensionFieldPresentation | ContentTypeFieldPresentation;
}
