/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ContentTypeField} from "./content-type-field";

/**
 * 
 * @export
 * @interface ContentType
 */
export interface ContentType {
    /**
     * identifying name of this Content type
     * @type {string}
     * @memberof ContentType
     */
    name: any;
    /**
     * the type of the content type (eg Document, FieldGroup) Valid values: Document, FieldGroup
     * @type {string}
     * @memberof ContentType
     */
    type: ContentTypeTypeEnum;
    /**
     * 
     * @type {ContentTypePresentation}
     * @memberof ContentType
     */
    presentation: any;
    /**
     * list of fields of this content type
     * @type {Array&lt;ContentTypeField&gt;}
     * @memberof ContentType
     */
    fields?: Array<ContentTypeField>;
    /**
     * 
     * @type {System}
     * @memberof ContentType
     */
    system?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum ContentTypeTypeEnum {
    Document = 'Document',
    FieldGroup = 'FieldGroup'
}

