/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * presentation properties of the content type 
 * @export
 * @interface ContentTypePresentation
 */
export interface ContentTypePresentation {
    /**
     * the layout of the content typeValid values: one-column, two-column, three-column, horizontal, two-column-mirrored
     * @type {string}
     * @memberof ContentTypePresentation
     */
    layout: ContentTypePresentationLayoutEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ContentTypePresentationLayoutEnum {
    OneColumn = 'one-column',
    TwoColumn = 'two-column',
    ThreeColumn = 'three-column',
    Horizontal = 'horizontal',
    TwoColumnMirrored = 'two-column-mirrored'
}

