/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DropdownFieldValdations
 */
export interface DropdownFieldValdations {
    /**
     * Id of a resource bundle that is used to fetch values
     * @type {string}
     * @memberof DropdownFieldValdations
     */
    inResourceBundle?: any;
    /**
     * inValues validation of the field. Expects an array of key-label values
     * @type {Array&lt;KeyLabel&gt;}
     * @memberof DropdownFieldValdations
     */
    inValues?: any;
}
