/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EmbeddedResourceDefaultValue
 */
export interface EmbeddedResourceDefaultValue {
    /**
     * the name of the file that is used as default value
     * @type {string}
     * @memberof EmbeddedResourceDefaultValue
     */
    filename: any;
    /**
     * the binary data of the file that is used as default value. This data has to be encoded using base64
     * @type {string}
     * @memberof EmbeddedResourceDefaultValue
     */
    binarydata: any;
    /**
     * the mimeType of the file to be uploaded
     * @type {string}
     * @memberof EmbeddedResourceDefaultValue
     */
    mimeType: any;
}
