/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface HtmlFieldPresentation
 */
export interface HtmlFieldPresentation {
    /**
     * the caption used for this field in UIs
     * @type {string}
     * @memberof HtmlFieldPresentation
     */
    caption: any;
    /**
     * the hint used for this field in UIs
     * @type {string}
     * @memberof HtmlFieldPresentation
     */
    hint: any;
    /**
     * layoutColumn index used for positioning the field
     * @type {number}
     * @memberof HtmlFieldPresentation
     */
    layoutColumn?: any;
    /**
     * ckEditorAppendedJson property of the field
     * @type {string}
     * @memberof HtmlFieldPresentation
     */
    ckEditorAppendedJson?: any;
    /**
     * ckEditorOverlayedJson property of the field
     * @type {string}
     * @memberof HtmlFieldPresentation
     */
    ckEditorOverlayedJson?: any;
}
