/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ImageLinkFieldPresentation
 */
export interface ImageLinkFieldPresentation {
    /**
     * the caption used for this field in UIs
     * @type {string}
     * @memberof ImageLinkFieldPresentation
     */
    caption: any;
    /**
     * the hint used for this field in UIs
     * @type {string}
     * @memberof ImageLinkFieldPresentation
     */
    hint: any;
    /**
     * layoutColumn index used for positioning the field
     * @type {number}
     * @memberof ImageLinkFieldPresentation
     */
    layoutColumn?: any;
    /**
     * the uploadEnabled used for this field in UIs
     * @type {boolean}
     * @memberof ImageLinkFieldPresentation
     */
    uploadEnabled?: any;
    /**
     * display type of the field. Valid values: AnyLink, ImageLink
     * @type {string}
     * @memberof ImageLinkFieldPresentation
     */
    displayType: ImageLinkFieldPresentationDisplayTypeEnum;
    /**
     * the lookupFolderTypes used for this field in UIs
     * @type {Array&lt;string&gt;}
     * @memberof ImageLinkFieldPresentation
     */
    lookupFolderTypes?: any;
    /**
     * the lastVisitedKey used for this field in UIs
     * @type {string}
     * @memberof ImageLinkFieldPresentation
     */
    lastVisitedKey?: any;
    /**
     * the lastVisitedEnabled used for this field in UIs
     * @type {boolean}
     * @memberof ImageLinkFieldPresentation
     */
    lastVisitedEnabled?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum ImageLinkFieldPresentationDisplayTypeEnum {
    Simple = 'Simple',
    Text = 'Text',
    Checkbox = 'Checkbox',
    RadioGroup = 'RadioGroup',
    Dropdown = 'Dropdown',
    MultiSelect = 'MultiSelect',
    AnyLink = 'AnyLink',
    ImageLink = 'ImageLink'
}

