/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * inValues validation of the field. Expects an array of key-label values
 * @export
 * @interface KeyLabel
 */
export interface KeyLabel {
    /**
     * key validation of the field. Expects a string value
     * @type {string}
     * @memberof KeyLabel
     */
    key: any;
    /**
     * label validation of the field. Expects a string value
     * @type {string}
     * @memberof KeyLabel
     */
    label: any;
}
