/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MultiSelectFieldPresentation
 */
export interface MultiSelectFieldPresentation {
    /**
     * the caption used for this field in UIs
     * @type {string}
     * @memberof MultiSelectFieldPresentation
     */
    caption: any;
    /**
     * the hint used for this field in UIs
     * @type {string}
     * @memberof MultiSelectFieldPresentation
     */
    hint: any;
    /**
     * layoutColumn index used for positioning the field
     * @type {number}
     * @memberof MultiSelectFieldPresentation
     */
    layoutColumn?: any;
    /**
     * display type of the field. Valid values: RadioGroup, Dropdown, MultiSelect
     * @type {string}
     * @memberof MultiSelectFieldPresentation
     */
    displayType: MultiSelectFieldPresentationDisplayTypeEnum;
    /**
     * multiSelectType type of the field.
     * @type {string}
     * @memberof MultiSelectFieldPresentation
     */
    multiSelectType?: MultiSelectFieldPresentationMultiSelectTypeEnum;
    /**
     * maxRowWithoutScrollbar type of the field.
     * @type {number}
     * @memberof MultiSelectFieldPresentation
     */
    maxRowWithoutScrollbar?: any;
    /**
     * multiSelectAllowOrder type of the field.
     * @type {boolean}
     * @memberof MultiSelectFieldPresentation
     */
    multiSelectAllowOrder?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum MultiSelectFieldPresentationDisplayTypeEnum {
    Simple = 'Simple',
    Text = 'Text',
    Checkbox = 'Checkbox',
    RadioGroup = 'RadioGroup',
    Dropdown = 'Dropdown',
    MultiSelect = 'MultiSelect',
    AnyLink = 'AnyLink',
    ImageLink = 'ImageLink'
}
/**
    * @export
    * @enum {string}
    */
export enum MultiSelectFieldPresentationMultiSelectTypeEnum {
    Selectlist = 'selectlist',
    Checkboxes = 'checkboxes',
    Palette = 'palette'
}

