/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MultiSelectAndRadioGroupFieldsValidations
 */
export interface MultiSelectAndRadioGroupFieldsValidations {
    /**
     * Id of a resource bundle that is used to fetch values
     * @type {string}
     * @memberof MultiSelectAndRadioGroupFieldsValidations
     */
    inResourceBundle?: any;
}
