/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RichTextFieldPresentation
 */
export interface RichTextFieldPresentation {
    /**
     * the caption used for this field in UIs
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    caption: any;
    /**
     * the hint used for this field in UIs
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    hint: any;
    /**
     * layoutColumn index used for positioning the field
     * @type {number}
     * @memberof RichTextFieldPresentation
     */
    layoutColumn?: any;
    /**
     * ckEditorAppendedJson property of the field
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    ckEditorAppendedJson?: any;
    /**
     * ckEditorOverlayedJson property of the field
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    ckEditorOverlayedJson?: any;
    /**
     * imagepickerBasePath property of the field
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    imagepickerBasePath?: any;
    /**
     * imagepickerType property of the field
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    imagepickerType?: any;
    /**
     * imagepickerNodetypes property of the field
     * @type {Array&lt;string&gt;}
     * @memberof RichTextFieldPresentation
     */
    imagepickerNodetypes?: any;
    /**
     * imagepickerLastVisitedEnabled property of the field
     * @type {boolean}
     * @memberof RichTextFieldPresentation
     */
    imagepickerLastVisitedEnabled?: any;
    /**
     * imagepickerLastVisitedGroupKey property of the field
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    imagepickerLastVisitedGroupKey?: any;
    /**
     * imagepickerLastVisitedNodetypes property of the field
     * @type {Array&lt;string&gt;}
     * @memberof RichTextFieldPresentation
     */
    imagepickerLastVisitedNodetypes?: any;
    /**
     * imagepickerPreferredImageVariant property of the field
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    imagepickerPreferredImageVariant?: any;
    /**
     * linkpickerBasePath property of the field
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    linkpickerBasePath?: any;
    /**
     * linkpickerType property of the field
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    linkpickerType?: any;
    /**
     * linkpickerNodetypes property of the field
     * @type {Array&lt;string&gt;}
     * @memberof RichTextFieldPresentation
     */
    linkpickerNodetypes?: any;
    /**
     * linkpickerLastVisitedEnabled property of the field
     * @type {boolean}
     * @memberof RichTextFieldPresentation
     */
    linkpickerLastVisitedEnabled?: any;
    /**
     * linkpickerLastVisitedGroupKey property of the field
     * @type {string}
     * @memberof RichTextFieldPresentation
     */
    linkpickerLastVisitedGroupKey?: any;
    /**
     * linkpickerLastVisitedNodetypes property of the field
     * @type {Array&lt;string&gt;}
     * @memberof RichTextFieldPresentation
     */
    linkpickerLastVisitedNodetypes?: any;
    /**
     * linkPickerLanguageContextAware property of the field
     * @type {boolean}
     * @memberof RichTextFieldPresentation
     */
    linkPickerLanguageContextAware?: any;
    /**
     * linkPickerOpenInNewWindowEnabled property of the field
     * @type {boolean}
     * @memberof RichTextFieldPresentation
     */
    linkPickerOpenInNewWindowEnabled?: any;
    /**
     * includeImageVariants property of the field
     * @type {Array&lt;string&gt;}
     * @memberof RichTextFieldPresentation
     */
    includeImageVariants?: any;
    /**
     * excludeImageVariants property of the field
     * @type {Array&lt;string&gt;}
     * @memberof RichTextFieldPresentation
     */
    excludeImageVariants?: any;
}
