/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SelectableFieldGroupDefaultValue
 */
export interface SelectableFieldGroupDefaultValue {
    /**
     * fields from FieldGroup or SelectableFieldGroup
     * @type {{ [key, string]: Array&lt;DefaultValue&gt;;}}
     * @memberof SelectableFieldGroupDefaultValue
     */
    fields: any;
    /**
     * the name of the default value type
     * @type {string}
     * @memberof SelectableFieldGroupDefaultValue
     */
    fieldGroupType: any;
}
