/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SelectableFieldGroupPresentation
 */
export interface SelectableFieldGroupPresentation {
    /**
     * the caption used for this field in UIs
     * @type {string}
     * @memberof SelectableFieldGroupPresentation
     */
    caption: any;
    /**
     * the hint used for this field in UIs
     * @type {string}
     * @memberof SelectableFieldGroupPresentation
     */
    hint: any;
    /**
     * layoutColumn index used for positioning the field
     * @type {number}
     * @memberof SelectableFieldGroupPresentation
     */
    layoutColumn?: any;
    /**
     * the way the picker buttons will be rendered. The valid values are 'links' (default) and 'dropdown': links: shows as many buttons as available compounds. When hitting a button, adds a new block of that compound type dropdown: presents a dropdown containing all the available compounds and an additional button to add an item of the selected compound of the dropdown.
     * @type {string}
     * @memberof SelectableFieldGroupPresentation
     */
    contentPickerType: SelectableFieldGroupPresentationContentPickerTypeEnum;
    /**
     * the valid values are 'false' (default) and 'true', it determines whether each item should add the field group name on top of it. When it's active, clicking on the name will collapse or expand the item.
     * @type {boolean}
     * @memberof SelectableFieldGroupPresentation
     */
    showFieldGroupNames: any;
}

/**
    * @export
    * @enum {string}
    */
export enum SelectableFieldGroupPresentationContentPickerTypeEnum {
    Links = 'links',
    Dropdown = 'dropdown'
}

