/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StringFieldPresentation
 */
export interface StringFieldPresentation {
    /**
     * the caption used for this field in UIs
     * @type {string}
     * @memberof StringFieldPresentation
     */
    caption: any;
    /**
     * the hint used for this field in UIs
     * @type {string}
     * @memberof StringFieldPresentation
     */
    hint: any;
    /**
     * layoutColumn index used for positioning the field
     * @type {number}
     * @memberof StringFieldPresentation
     */
    layoutColumn?: any;
    /**
     * display type of the field. Valid values: Simple, Text
     * @type {string}
     * @memberof StringFieldPresentation
     */
    displayType: StringFieldPresentationDisplayTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum StringFieldPresentationDisplayTypeEnum {
    Simple = 'Simple',
    Text = 'Text',
    Checkbox = 'Checkbox',
    RadioGroup = 'RadioGroup',
    Dropdown = 'Dropdown',
    MultiSelect = 'MultiSelect',
    AnyLink = 'AnyLink',
    ImageLink = 'ImageLink'
}

