/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StringFieldValidations
 */
export interface StringFieldValidations {
    /**
     * maxLength validation of the field. Expects an integer value
     * @type {number}
     * @memberof StringFieldValidations
     */
    maxLength?: any;
    /**
     * maxRow validation of the field. Expects an integer value
     * @type {number}
     * @memberof StringFieldValidations
     */
    maxRow?: any;
}
