/* tslint:disable */
/* eslint-disable */
/**
 * Content Type Management API
 * The Content Type Management API enables brX developers to manage content types through a set of endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * system properties
 * @export
 * @interface System
 */
export interface System {
    /**
     * 
     * @type {string}
     * @memberof System
     */
    createdBy?: any;
    /**
     * 
     * @type {Date}
     * @memberof System
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof System
     */
    updatedBy?: any;
    /**
     * 
     * @type {Date}
     * @memberof System
     */
    updatedAt?: any;
}
